mysql:
  dns: root:*******@tcp(127.0.0.1:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local #需要替换Mysql密码
redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
oss:
  Endpoint: "oss-cn-beijing.aliyuncs.com"
  AccessKeyId: "****" #需要替换你的阿里云key
  AccessKeySecret: "***"
  Bucket : "ginimchat"
timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间   
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线 
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H